In [3]:
#import all required libraries
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [4]:
#load the trained model, scaler pickle, onehot
model = load_model('model.h5')

#load the encoder and scaler
with open('label_encoder_geo.pkl', 'rb') as file:
    label_encoder_geo = pickle.load(file)

with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

In [5]:
input_data = {
    "CreditScore":600,
    "Geography": "France",
    "Gender": "Male",
    "Age" : 40,
    "Tenure":3,
    "Balance":60000,
    "NumOfProducts":2,
    "HasCrCard":1,
    "IsActiveMember":1,
    "EstimatedSalary":50000
}

In [6]:
# One-hot encode 'Geography'
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded

c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [7]:
geo_encoded_df = pd.DataFrame(geo_encoded, columns = label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [8]:
input_df = pd.DataFrame([input_data])
input_df

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France   Male   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [9]:
#combine one-hot encoded columns with input data
input_data = pd.concat([input_df.reset_index(drop = True), geo_encoded_df], axis = 1)
input_data

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France   Male   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  Geography_France  \
0          1               1            50000               1.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0

In [10]:
#Encode categorical variables
input_data['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_data.head()

CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France       1   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  Geography_France  \
0          1               1            50000               1.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0

In [11]:
input_data = input_data.drop(columns = 'Geography', axis = 1)
input_data

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600       1   40       3    60000              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0   

   Geography_Spain  
0              0.0

In [12]:
## Scaling input data
input_scaler = scaler.transform(input_data)
input_scaler

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [13]:
#predict churn
prediction = model.predict(input_scaler)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step


array([[0.06058558]], dtype=float32)

In [14]:
prediction_prob = prediction[0][0]
prediction_prob

np.float32(0.060585584)

In [15]:
if prediction_prob > 0.5:
    print("The customer is likely to churn.")
else:
    print('The customer is not likely to churn')

The customer is not likely to churn
