# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [7]:
#1
import numpy as np
arr = np.random.randint(1, 21, size = (5, 5))
print(arr)
arr[:,2] = 1
print(arr)

[[11 12  1 20 14]
 [17 17 19 15  2]
 [ 1 16 20 17 11]
 [16 13 20  3  1]
 [13  5 12 17  5]]
[[11 12  1 20 14]
 [17 17  1 15  2]
 [ 1 16  1 17 11]
 [16 13  1  3  1]
 [13  5  1 17  5]]


In [13]:
#2
arr = np.arange(1, 17).reshape(4, 4)
print("Original Array")
print(arr)
print("Modified Array")
np.fill_diagonal(arr, 0)
print(arr)


Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [19]:
arr = np.arange(1, 37).reshape(6,6)
print('Original Array:\n', arr)
sub_arr = arr[3:6, 1:4]
print("Sub Array:\n", sub_arr)

Original Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub Array:
 [[20 21 22]
 [26 27 28]
 [32 33 34]]


In [ ]:
# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

In [24]:
a = np.random.random(size = (5,5))
print("Original Array:\n", a)
np.concatenate((a[0,:], a[-1,:], a[1:-1,0], a[1:-1, -1]))

Original Array:
 [[0.71247307 0.35946098 0.85142153 0.21117999 0.74064899]
 [0.69524678 0.28652338 0.886666   0.62095892 0.28479108]
 [0.85454524 0.45461918 0.19915237 0.58443353 0.10816653]
 [0.83785465 0.86912659 0.52224396 0.85225702 0.29303183]
 [0.67159016 0.40260661 0.52757337 0.47296527 0.30113298]]


array([0.71247307, 0.35946098, 0.85142153, 0.21117999, 0.74064899,
       0.67159016, 0.40260661, 0.52757337, 0.47296527, 0.30113298,
       0.69524678, 0.85454524, 0.83785465, 0.28479108, 0.10816653,
       0.29303183])

### Assignment 3: Array Operations

##### 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.



In [28]:
arr1 = np.random.random(size = (3, 4))
arr2 = np.random.random(size = (3, 4))
print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1/arr2)

Addition: [[1.16755065 1.38683824 0.56021676 1.55992925]
 [0.73905937 1.23604376 0.7607068  1.21979136]
 [1.13715019 0.92055511 0.84249599 1.46707578]]
Subtraction: [[-0.29233133 -0.56891032  0.47546859  0.18496167]
 [-0.71851807  0.00517751  0.0483978   0.72042121]
 [-0.34359392  0.58644572  0.50970768  0.32996161]]
Multiplication: [[0.31942923 0.39991534 0.02194311 0.59979211]
 [0.00748513 0.38194434 0.14408312 0.24222106]
 [0.29376345 0.12587578 0.11249939 0.51085917]]
Division: [[ 0.59951375  0.41821732 12.22074012  1.26904151]
 [ 0.01409276  1.00841278  1.13588991  3.88531942]
 [ 0.53591722  4.51050138  4.06325471  1.58034913]]


##### 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [35]:
arr = np.arange(1, 17).reshape(4, 4)
row_wise_sum = np.sum(arr, axis = 1)
col_wise_sum = np.sum(arr, axis = 0)
print("Original Array:\n", arr)
print("\nRow Wise sum:\n", row_wise_sum)
print("\n Column Wise sum:\n", col_wise_sum)


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row Wise sum:
 [10 26 42 58]

 Column Wise sum:
 [28 32 36 40]


### Assignment 4: Statistical Operations

##### 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [45]:
#arr = np.random.random(size = (5,5))
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
var = np.var(arr)
print(f"Mean: {mean:.4f}")
print(f"Median: {median:.4f}")
print(f"Standard Deviation: {std_dev:.4f}")
print(f"Variance: {var:.4f}")

Mean: 0.4286
Median: 0.4375
Standard Deviation: 0.2099
Variance: 0.0441


##### 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [46]:
arr = np.arange(1,10).reshape(3,3)
mean = np.mean(arr)
std_dev = np.std(arr)
norm_arr = (arr - mean) / std_dev
print("Original Array:\n", arr)
print("Normalized Array:\n", norm_arr)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [48]:
np.random.random(3)

array([0.91986068, 0.61610156, 0.73894086])

In [52]:
arr = np.random.random(size = (3,3))
print("Original Array:\n", arr,"\n")
arr1 = np.random.random(3)
print("1D array:\n", arr1, "\n")
broadcast_arr = arr + arr1
print("Broadcast Array:\n", broadcast_arr)

Original Array:
 [[0.8957944  0.91578979 0.73378607]
 [0.31330423 0.13946074 0.34300231]
 [0.6247312  0.81997992 0.70038478]] 

1D array:
 [0.28431399 0.10649958 0.12071383] 

Broadcast Array:
 [[1.1801084  1.02228937 0.8544999 ]
 [0.59761822 0.24596032 0.46371614]
 [0.90904519 0.9264795  0.82109861]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [54]:
import numpy as np
arr = np.random.random(size=(4, 4))
print("Original Array:\n", arr, "\n")
arr1 = np.random.random(4)
print("1D Array:\n", arr1, "\n")
broadcast_arr = arr - arr1
print("Broadcast Array:\n", broadcast_arr)

Original Array:
 [[0.94815307 0.48784045 0.4383918  0.53361502]
 [0.40680259 0.51476583 0.43269924 0.43070162]
 [0.57185762 0.61625811 0.43494064 0.51992761]
 [0.00386951 0.54017354 0.3386365  0.26855029]] 

1D Array:
 [0.63012476 0.92214118 0.92179674 0.79783653] 

Broadcast Array:
 [[ 0.31802832 -0.43430074 -0.48340494 -0.26422151]
 [-0.22332217 -0.40737535 -0.4890975  -0.36713492]
 [-0.05826714 -0.30588307 -0.4868561  -0.27790893]
 [-0.62625525 -0.38196764 -0.58316024 -0.52928624]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [56]:
arr = np.arange(1, 10).reshape(3, 3)
det = np.linalg.det(arr)
inv = np.linalg.inv(arr)
ev = np.linalg.eigvals(arr)
print("Determinanat:", det)
print("Inverse:\n", inv)
print("Eigen Values:\n", ev)

Determinanat: -9.51619735392994e-16
Inverse:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
Eigen Values:
 [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [65]:
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(8, 14).reshape(3, 2)
print("Original Array1:\n",arr1, "\n")
print("Original Array2:\n", arr2)
print("Array Multiplication:\n", np.matmul(arr1, arr2))

Original Array1:
 [[1 2 3]
 [4 5 6]] 

Original Array2:
 [[ 8  9]
 [10 11]
 [12 13]]
Array Multiplication:
 [[ 64  70]
 [154 169]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [58]:
arr = np.arange(1,10).reshape(3, 3)
arr1 = arr.reshape(1, 9)
arr2 = arr.reshape(9, 1)
print("Original Array:\n", arr)
print("Array (1,9):", arr1, "\n")
print("Array (9, 1):", arr2)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array (1,9): [[1 2 3 4 5 6 7 8 9]] 

Array (9, 1): [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [68]:
arr = np.random.random(size = (5, 5))
print("Original Array:\n", arr, "\n")
flatten_arr = arr.flatten()
print("Flatten Array:\n", flatten_arr)
reshaped_arr = arr.reshape(5, 5)
print("Reshaped Array:\n", reshaped_arr)

Original Array:
 [[0.425551   0.61046716 0.82499617 0.65918648 0.69188642]
 [0.0130144  0.21366642 0.86276    0.78076982 0.43726113]
 [0.4606493  0.25407978 0.04666706 0.59268692 0.41396552]
 [0.94220719 0.93168059 0.20763569 0.11653225 0.9375188 ]
 [0.78460473 0.8295016  0.85663414 0.09339646 0.24204544]] 

Flatten Array:
 [0.425551   0.61046716 0.82499617 0.65918648 0.69188642 0.0130144
 0.21366642 0.86276    0.78076982 0.43726113 0.4606493  0.25407978
 0.04666706 0.59268692 0.41396552 0.94220719 0.93168059 0.20763569
 0.11653225 0.9375188  0.78460473 0.8295016  0.85663414 0.09339646
 0.24204544]
Reshaped Array:
 [[0.425551   0.61046716 0.82499617 0.65918648 0.69188642]
 [0.0130144  0.21366642 0.86276    0.78076982 0.43726113]
 [0.4606493  0.25407978 0.04666706 0.59268692 0.41396552]
 [0.94220719 0.93168059 0.20763569 0.11653225 0.9375188 ]
 [0.78460473 0.8295016  0.85663414 0.09339646 0.24204544]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [71]:
arr = np.random.random(size = (5, 5))
print("Original Array:\n", arr, "\n")
corners = arr[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corners of Array:\n", corners)

Original Array:
 [[0.01040067 0.45156412 0.36370761 0.05834776 0.87917158]
 [0.75221597 0.12564877 0.20075088 0.59879498 0.3263249 ]
 [0.28374191 0.99877537 0.16647166 0.22629939 0.17609164]
 [0.81342598 0.66106937 0.26766892 0.49528942 0.61029768]
 [0.8252026  0.6664278  0.92445786 0.7438217  0.0664552 ]] 

Corners of Array:
 [0.01040067 0.87917158 0.8252026  0.0664552 ]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [76]:
arr = np.random.randint(1, 20, size = (4, 4))
print("Original Array:\n", arr, "\n")
arr[arr>10] = 10
print("Modified Array:\n", arr)


Original Array:
 [[ 9 11 10  6]
 [11 15 14 14]
 [ 4  9  3  2]
 [ 4  6  8 17]] 

Modified Array:
 [[ 9 10 10  6]
 [10 10 10 10]
 [ 4  9  3  2]
 [ 4  6  8 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


In [78]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.5), ('Charlie', 20, 65.2)], dtype = data_type)
print("Original Array:")
print(data)
sorted_data = np.sort(data, order = "age")
print("Sorted_Array:")
print(sorted_data)

Original Array:
[('Alice', 25, 55.5) ('Bob', 30, 85.5) ('Charlie', 20, 65.2)]
Sorted_Array:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.5)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [80]:
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1,2), (3,4), (5, 6)], dtype=data_type)
print("Original data:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original data:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [91]:
import numpy.ma as ma
data = np.random.randint(1, 21, size = (4, 4))
print("Original Array:")
print(data)
masked_data = ma.masked_greater(data, 10)
print("Masked Array:")
print(masked_data)

### compute the sum of unmasked
print("Sum of unmasked elements:")
print(masked_data.sum())

Original Array:
[[ 6  4  7  6]
 [ 4 14  6  4]
 [18  3 12  3]
 [15  1  1 18]]
Masked Array:
[[6 4 7 6]
 [4 -- 6 4]
 [-- 3 -- 3]
 [-- 1 1 --]]
Sum of unmasked elements:
45


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [99]:
arr = np.random.random((3,3))
print("Original Array:")
print(arr)

masked_arr = ma.masked_array(arr, mask=np.eye(3, dtype = bool))
print("Masked Array:")
print(masked_arr)

unmasked_mean = masked_arr.mean()
masked_arr2 = masked_arr.filled(unmasked_mean)
print("Filled Array:")
print(masked_arr2)

Original Array:
[[0.18378308 0.09365802 0.04868147]
 [0.59728643 0.26907059 0.59644719]
 [0.85285704 0.08316957 0.60514448]]
Masked Array:
[[-- 0.09365802127369782 0.04868146724868494]
 [0.5972864322175766 -- 0.5964471937417926]
 [0.8528570391996336 0.08316956521410757 --]]
Filled Array:
[[0.37868329 0.09365802 0.04868147]
 [0.59728643 0.37868329 0.59644719]
 [0.85285704 0.08316957 0.37868329]]
